### ISSUE TITLE
core.presentation.list api with search parameter

### ISSUE THREAD

**Issue by skaluva** [Rise-Vision/core-api#27]
Hi,
Currently core.presentation.list, api with search query parameter expects exact name of the presentation. For example if i give search=name: Global_1 , it returns the presentation with name Global_1. 

GET https://rvacore-test.appspot.com/_ah/api/core/v1/presentations?search=name%3A+Global_1

But in my case, i have several presentations that Start with "Global". Is there any way, i can pass partial name and get the presentations that matches the criteria. I want some thing like this:

GET https://rvacore-test.appspot.com/_ah/api/core/v1/presentations?search=name%3A+Global

Otherwise i need to iterate over all presentations and filter out presentations that start with "Global" :( which i'm doing currently now. But presentations are growing day by day and this is making the application slow.

Thanks in advance.

**Comment by alexey-rise** [comment]
There is currently no way to search for values that start with a character or a sequence of characters (e.g. search string "G" or "Glo" would not match "Global_1").

The search functionality we use *does* support search by parts of the field, but the values are indexed by word and unfortunately "_" is not a word separator. 

For example, if the name were "Global 1" or Global-1", the search by "Global" would work.

We also support search by similar words, so the search string "~Global" would match "Globals", "Local+Global", but not "Globalization".  

I hope this answers your question.

**Comment by skaluva** [comment]
Thanks a lot. Will use convention as Global-1, Global-2 etc., instead of Global_1 etc. It would be good if you can document the same (ie., you support word wise search filter separated by space or hyphen) in the developer documentation. I searched everywhere, couldn't find this information. So asked here.

Anyways, the solution you suggested solves my problem.
