### ISSUE TITLE
Console display status not working

### ISSUE THREAD

**Issue by xelio91** [Rise-Vision/core-api#30]
Hello,
In the core console, after listing all company's displays, the display's status (online/offline) does not work correctly: all of them seems are offline but many of them are online.

![screen](https://user-images.githubusercontent.com/11650680/27027840-2178188a-4f63-11e7-91e9-f048615c6676.jpg)

**Comment by rodrigopavezi** [comment]
Hi @xelio91, we have changed our onlineStatus to work with a real time system for better performance and reliability. So core api will not retrieve it anymore. I hope this information is helpful if not let me know.

Cheers

Rodrigo
